### PR TITLE
18735 - rename pre-assembly-nodejs-static...

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

18735 - rename pre-assembly-nodejs-static tarball to nexe-cache; use new NEXE flags from upstream Che 7.23; pack/unpack from /tmp/nexe-cache instead of HOME/pre-assembly-nodejs-static

Change-Id: I19659464c2d5bd8e7bba86a306fb81cf82305e53
Signed-off-by: nickboldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
N/A (or see commit messasge above for issue number)

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by benoitf** [comment]
You should add a custom `builder-nexe-setup.dockerfile` file based on https://github.com/eclipse/che-theia/blob/master/dockerfiles/theia-endpoint-runtime-binary/docker/ubi8/builder-nexe-setup.dockerfile file (where we don't do git clone but just unpack /tmp/nexe content )

**Comment by nickboldt** [comment]
thanks, added another commit. look OK?

**Review by benoitf — APPROVED** [review]
let's try with that
I may take a look tomorrow

**Comment by nickboldt** [comment]
also related: https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/merge_requests/110

**Comment by nickboldt** [comment]
merged, running in https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/CRW_CI/job/crw-theia-sources_2.6/2/console to verify

**Pull request merged**
